config/routes.rb
Rails.application.routes.draw do

  get 'kamonups', to: 'kamon_ups#index'
  get '/kamonups/:id', to: 'kamon_ups#show'

  mount Ckeditor::Engine => '/ckeditor'
  root 'top#index'

  get 'static_pages/help'
  get 'static_pages/pictures'
  get 'static_pages/design'
  get 'static_pages/markinfos'

namespace :rayadmin do
  root 'admins#home'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users
  resources :customers
  resources :ordersheets
  resources :notes
  resources :sprices
  resources :pimages
  resources :markinfos
  resources :kamons
  resources :performs
  
  resources :projects do
    resources :tasks, only: [:create, :destroy]
  end
  
  post '/projects/:project_id/tasks/:id/toggle' => 'tasks#toggle'
  
  resources 'customers', only: :index do
    collection { post :import }
  end
end

end

app/controllers/rayadmin/admins_controller.rb
class Rayadmin::AdminsController < Rayadmin::RayadminController
  def home
    if not logged_in?
      redirect_to rayadmin_login_path
    end
  end
end

app/controllers/rayadmin/customers_controller.rb
class Rayadmin::CustomersController < Rayadmin::RayadminController
    
    def index
        # @customers = Customer.all
        @q = Customer.ransack(params[:q])
        @customers = @q.result
        
        respond_to do |format|
            format.html
            format.csv { send_data @customers.to_csv }
            format.xls { send_data @customers.to_csv(col_sep: "\t") }
        end
        
    end
    
    def new
        @customer = Customer.new
    end
    
    def show
        @customer = Customer.find params[:id]
    end
    
    def edit
        @customer = Customer.find params[:id]
    end
    
    def create
        @customer = Customer.new(customer_params)
            if @customer.save
                redirect_to customer_path(@customer) , notice: 'メッセージを保存しました'
             else
                @customers = Customer.all
                flash.now[:alert] = "メッセージの保存に失敗しました。"
                render :new
            end
        
    end
    
    def update
        @customer = Customer.find params[:id]
        if @customer.update(customer_params)
            redirect_to [:rayadmin, @customer]
        else
            render 'edit'
        end
    end
    def destroy
        @customer = Customer.find params[:id]
        @customer.destroy
        redirect_to rayadmin_customers_path, notice: '削除しました。'
    end
    
    def import
        # fileはtmpに自動で一時保存される
        Customer.import(params[:file])
        redirect_to root_url, notice: "商品を追加しました。"
    end
    
    private
    
    def customer_params
        params.require(:customer).permit(:name1, :name2, :kana1, :kana2, :zip, :address1, :address2, :address3, :tel1, :tel2, :fax, :email, :remark, :danjo, :birth, :piccus, :groupcus, :kubun, :maildm, :piccus_cache)
    end
    
end

app/controllers/rayadmin/kamons_controller.rb
class Rayadmin::KamonsController < Rayadmin::RayadminController
  before_action :set_kamon, only: [:show, :edit, :update, :destroy]
  before_action :set_kamon_tags_to_gon, only: [:edit]
  before_action :set_available_tags_to_gon, only: [:new, :edit]

  # GET /kamons
  def index
    @kamons = params[:tag].present? ? Kamon.tagged_with(params[:tag]) : Kamon.all
    @kamons = @kamons.all.includes(:tags)
    
  end

  # GET /kamons/1
  def show
  end

  # GET /kamons/new
  def new
    @kamon = Kamon.new
  end

  # GET /kamons/1/edit
  def edit
  end

  # POST /kamons
  def create
    @kamon = Kamon.new(kamon_params)

    if @kamon.save
      redirect_to [:rayadmin, @kamon], notice: 'Kamon was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /kamons/1
  def update
    if @kamon.update(kamon_params)
      redirect_to [:rayadmin, @kamon], notice: 'Kamon was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /kamons/1
  def destroy
    @kamon.destroy
    redirect_to rayadmin_kamons_url, notice: 'Kamon was successfully destroyed.'
  end
  
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kamon
      @kamon = Kamon.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def kamon_params
      params.require(:kamon).permit(:title, :discription, :kamonpic, :kamonpic_cache, :tag_list)
    end
    def set_kamon_tags_to_gon
      gon.kamon_tags = @kamon.tag_list
    end
    def set_available_tags_to_gon
      gon.available_tags = Kamon.tags_on(:tags).pluck(:name)
    end
end

app/controllers/rayadmin/markinfos_controller.rb
class Rayadmin::MarkinfosController < Rayadmin::RayadminController
  before_action :set_markinfo, only: [:show, :edit, :update, :destroy]

  # GET /markinfos
  def index
    @markinfos = Markinfo.all
  end

  # GET /markinfos/1
  def show
  end

  # GET /markinfos/new
  def new
    @markinfo = Markinfo.new
  end

  # GET /markinfos/1/edit
  def edit
  end

  # POST /markinfos
  def create
    @markinfo = Markinfo.new(markinfo_params)

    if @markinfo.save
      redirect_to [:rayadmin, @markinfo], notice: 'Markinfo was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /markinfos/1
  def update
    if @markinfo.update(markinfo_params)
      redirect_to [:rayadmin, @markinfo], notice: 'Markinfo was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /markinfos/1
  def destroy
    @markinfo.destroy
    redirect_to rayadmin_markinfos_url, notice: 'Markinfo was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_markinfo
      @markinfo = Markinfo.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def markinfo_params
      params.require(:markinfo).permit(:title, :description, :user_id)
    end
end

app/controllers/rayadmin/notes_controller.rb
class Rayadmin::NotesController < Rayadmin::RayadminController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  def index
    @notes = Note.all
  end

  def show
  end

  def new
    @note = Note.new
  end

  def edit
  end

  def create
    @note = Note.new(note_params)
    if @note.save
      redirect_to rayadmin_note_path(@note)
    else
      render 'new'
    end
    
  end

  def update
      if @note.update(note_params)
        redirect_to [:rayadmin, @note], notice: 'Note was successfully updated.'
      else
        render :edit
      end
  end


  def destroy
    @note.destroy
      redirect_to rayadmin_notes_path, notice: 'Note was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :content, :user_id)
    end
end

app/controllers/rayadmin/ordersheets_controller.rb
class Rayadmin::OrdersheetsController < Rayadmin::RayadminController
  def index
  end
  
  def new
    @ordersheet = Ordersheet.new
  end
end

app/controllers/rayadmin/performs_controller.rb
class Rayadmin::PerformsController < Rayadmin::RayadminController
  before_action :set_perform, only: [:show, :edit, :update, :destroy]
  before_action :set_perform_tags_to_gon, only: [:edit]
  before_action :set_available_tags_to_gon, only: [:new, :edit]

  # GET /performs
  def index
    @performs = params[:tag].present? ? Perform.tagged_with(params[:tag]) : Perform.all
    @performs = @performs.all.includes(:tags)
  end

  # GET /performs/1
  def show
  end

  # GET /performs/new
  def new
    @perform = Perform.new
  end

  # GET /performs/1/edit
  def edit
  end

  # POST /performs
  def create
    @perform = Perform.new(perform_params)

    if @perform.save
      redirect_to [:rayadmin, @perform], notice: 'Perform was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /performs/1
  def update
    if @perform.update(perform_params)
      redirect_to [:rayadmin, @perform], notice: 'Perform was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /performs/1
  def destroy
    @perform.destroy
    redirect_to rayadmin_performs_url, notice: 'Perform was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perform
      @perform = Perform.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def perform_params
      params.require(:perform).permit(:title, :description, :performimage, :performimage_cache, :tag_list)
    end
    
    def set_perform_tags_to_gon
      gon.perform_tags = @perform.tag_list
    end
    def set_available_tags_to_gon
      gon.available_tags = Perform.tags_on(:tags).pluck(:name)
    end
    
end

app/controllers/rayadmin/pimages_controller.rb
class Rayadmin::PimagesController < Rayadmin::RayadminController
  before_action :set_pimage, only: [:show, :edit, :update, :destroy]

  # GET /pimages
  def index
    @pimages = Pimage.all
  end

  # GET /pimages/1
  def show
  end

  # GET /pimages/new
  def new
    @pimage = Pimage.new
  end

  # GET /pimages/1/edit
  def edit
  end

  # POST /pimages
  def create
    @pimage = Pimage.new(pimage_params)

    if @pimage.save
      redirect_to [:rayadmin, @pimage], notice: 'Pimage was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /pimages/1
  def update
    if @pimage.update(pimage_params)
      redirect_to [:rayadmin, @pimage], notice: 'Pimage was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /pimages/1
  def destroy
    @pimage.destroy
    redirect_to rayadmin_pimages_url, notice: 'Pimage was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pimage
      @pimage = Pimage.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def pimage_params
      params.require(:pimage).permit(:ptitle, :purl, :pcomment, :ptag, :pimage, :pimage_cache)
    end
end

app/controllers/rayadmin/projects_controller.rb
class Rayadmin::ProjectsController < Rayadmin::RayadminController
    
    before_action :set_project, only: [:show, :edit, :update, :destroy]
    
    def index
        @projects = Project.all
    end
    
    def show
    end
    
    def new
        @project = Project.new
    end
    
    def create
        @project = Project.new(project_params)
        if @project.save
          redirect_to rayadmin_projects_path
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @project.update(project_params)
          redirect_to rayadmin_projects_path
        else
            render 'edit'
        end
    end
    
    def destroy
        @project.destroy
        redirect_to rayadmin_projects_path
    end
    
    
    
    private
        def project_params
            params.require(:project).permit(:title)
        end
        
        def set_project
            @project = Project.find(params[:id])
        end
        
    
    
end

app/controllers/rayadmin/rayadmin_controller.rb
class Rayadmin::RayadminController < ApplicationController
    layout 'rayadmin.html.erb'
end

app/controllers/rayadmin/sessions_controller.rb
class Rayadmin::SessionsController < Rayadmin::RayadminController
  def new
  end
  
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "#{@user.name}として、ログインしました。"
      redirect_to [:rayadmin, @user]
    else
      flash[:danger] = "メールアドレスかパスワードが一致しません"
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to rayadmin_login_path
  end
  
end

app/controllers/rayadmin/sprices_controller.rb
class Rayadmin::SpricesController < Rayadmin::RayadminController
  before_action :set_sprice, only: [:show, :edit, :update, :destroy]

  # GET /sprices
  def index
    @sprices = Sprice.all
  end

  # GET /sprices/1
  def show
  end

  # GET /sprices/new
  def new
    @sprice = Sprice.new
  end

  # GET /sprices/1/edit
  def edit
  end

  # POST /sprices
  def create
    @sprice = Sprice.new(sprice_params)

    if @sprice.save
      redirect_to [:rayadmin, @sprice], notice: 'Sprice was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /sprices/1
  def update
    if @sprice.update(sprice_params)
      redirect_to [:rayadmin, @sprice], notice: 'Sprice was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /sprices/1
  def destroy
    @sprice.destroy
    redirect_to sprices_url, notice: 'Sprice was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sprice
      @sprice = Sprice.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def sprice_params
      params.require(:sprice).permit(:teikyo, :acompany, :skuc, :jproduct, :eproduct, :pnumber, :p1cos, :p2cos, :p3cos, :p4cos)
    end
end

app/controllers/rayadmin/tasks_controller.rb
class Rayadmin::TasksController < Rayadmin::RayadminController
    
    def create
        @project = Project.find(params[:project_id])
        @task = @project.tasks.create(task_params)
        redirect_to rayadmin_project_path(@project.id)
    end
    
    def destroy
        @task = Task.find(params[:id])
        @task.destroy
        redirect_to rayadmin_project_path(params[:project_id])
    end
    
    def toggle
        render nothing: true
        @task = Task.find(params[:id])
        @task.done = !@task.done
        @task.save
        #redirect_to rayadmin_project_path(params[:project_id])
    end
    
  private
  
    def task_params
        params.require(:task).permit(:title)
    end
    
end

app/controllers/rayadmin/users_controller.rb
class Rayadmin::UsersController < Rayadmin::RayadminController
  def index
    # @users = User.all
    @q = User.ransack(params[:q])
    @users = @q.result
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    # file = params[:user][:image]
      # @user.set_image(file)
    
     if @user.save
       flash[:success] = "Welcome to the Sample App!"
       redirect_to [:rayadmin, @user]
     else
       render 'new'
     end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
        @user = User.find params[:id]
        # @user.set_image(file)
        if @user.update(user_params)
            redirect_to [:rayadmin, @user]
        else
            render 'edit'
        end
  end
    def destroy
        @user = User.find params[:id]
        @user.destroy
        redirect_to rayadmin_users_path, notice: '削除しました。'
    end
  
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  
end

app/controllers/rayadmins/customers_controller.rb
class Rayadmin::CustomersController < RayadminsController
    
    def index
        # @customers = Customer.all
        @q = Customer.ransack(params[:q])
        @customers = @q.result
        
        respond_to do |format|
            format.html
            format.csv { send_data @customers.to_csv }
            format.xls { send_data @customers.to_csv(col_sep: "\t") }
        end
        
    end
    
    def new
        @customer = Customer.new
    end
    
    def show
        @customer = Customer.find params[:id]
    end
    
    def edit
        @customer = Customer.find params[:id]
    end
    
    def create
        @customer = Customer.new(customer_params)
            if @customer.save
                redirect_to customer_path(@customer) , notice: 'メッセージを保存しました'
             else
                @customers = Customer.all
                flash.now[:alert] = "メッセージの保存に失敗しました。"
                render :new
            end
        
    end
    
    def update
        @customer = Customer.find params[:id]
        if @customer.update(customer_params)
            redirect_to @customer
        else
            render 'edit'
        end
    end
    def destroy
        @customer = Customer.find params[:id]
        @customer.destroy
        redirect_to customers_path, notice: '削除しました。'
    end
    
    def import
        # fileはtmpに自動で一時保存される
        Customer.import(params[:file])
        redirect_to root_url, notice: "商品を追加しました。"
    end
    
    private
    
    def customer_params
        params.require(:customer).permit(:name1, :name2, :kana1, :kana2, :zip, :address1, :address2, :address3, :tel1, :tel2, :fax, :email)
    end
    
end

app/controllers/rayadmins/sessions_controller.rb
class Rayadmin::SessionsController < RayadminsController
  def new
  end
  
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "{@user.name}として、ログインしました。"
      redirect_to @user
    else
      flash[:danger] = "メールアドレスかパスワードが一致しません"
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
  
end

app/helpers/rayadmin/customers_helper.rb
module Rayadmin::CustomersHelper
end

app/helpers/rayadmin/kamons_helper.rb
module Rayadmin::KamonsHelper
end

app/helpers/rayadmin/markinfos_helper.rb
module Rayadmin::MarkinfosHelper
end

app/views/rayadmin/performs/_form.html.erb
  <div class="box">  
    <div class="box-body">
      <%= form_for([:rayadmin, @perform]) do |f| %>
        <% if @perform.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@perform.errors.count, "error") %> prohibited this pimage from being saved:</h2>
      
            <ul>
            <% @perform.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
      
        <div class="form-group">
          <label for="tag" class="col col-xs-12 col-sm-4 col-md-3 control-label">タグ</label>
          <div class="col col-xs-10">
            <ul id="perform-tags"></ul>
          </div>
          <div class="col-xs-offset-2 col-sm-offset-2 col-md-offset-3"></div>
        </div>
        <div class="form-group">
          <label for="performimage" class="col col-xs-12 col-sm-4 col-md-3 control-label">画像</label>
            <div class="col col-xs-10">
              <%= image_tag @perform.performimage.url if @perform.performimage? %>
              <%= f.file_field :performimage %>
              <%= f.hidden_field :performimage_cache %>
            </div>
            <div class="col-xs-offset-2 col-sm-offset-2 col-md-offset-3"></div>
        </div>
        <div class="form-group">
          <label for="title" class="col col-xs-12 col-sm-4 col-md-3 control-label spacer10">タイトル</label>
            <div class="col col-xs-10">
              <%= f.text_field :title, {class:"form-control"} %>
            </div>
          <div class="col-xs-offset-2 col-sm-offset-2 col-md-offset-3"></div>
        </div>
        <div class="form-group">
          <label for="discription" class="col col-xs-12 col-sm-4 col-md-3 control-label spacer10">説明</label>
            <div class="col col-xs-10">
              <%= f.cktext_area :description, {class:"form-control"} %>
            </div>
            <div class="col-xs-offset-2 col-sm-offset-2 col-md-offset-3"></div>
        </div><br>
        <div class="form-group">
            <div class="col col-xs-10">
            <%= f.submit class: "btn btn-primary spacer10" %>
            </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/rayadmin/performs/_tags.html.erb
<% tags.each do |tag| %>
  <%= link_to "#{tag.name} (#{tag.taggings_count})", rayadmin_performs_path(tag: tag.name) %>
<% end %>

app/views/rayadmin/performs/edit.html.erb
<h1>写真集編集</h1>

<%= render 'form' %>

<%= link_to 'Show', [:rayadmin, @perform] %> |
<%= link_to 'Back', rayadmin_performs_path %>

app/views/rayadmin/performs/index.html.erb
<section class="content-header">
<h1>写真集（実績）</h1>
</section>

<section class="content">
    <div class="box">
        <div class="box-header">
            <%= link_to "新規作成", new_rayadmin_perform_path %>
        </div>
        <div class="box-body">
          <div class="row">
            <% @performs.each do |perform| %>
            
              <div class="col-xs-6 col-md-2">
                
            		<div id="img-box" class="thumbnail">
            			<%= image_tag perform.performimage.thumb.url %>
            			<div id="img-box-mini"><p id="img-box-text"><%= link_to perform.title, rayadmin_perform_path(perform.id) %></p>
            			</div>
            			<div id="img-box-mini-footer"><p class="img-box-tag"><%= render partial: 'tags', locals: { tags: perform.tags } %></p></div>
            		</div>
            	</div>
            	
            <% end %>
          </div>
          
        </div>
    </div>
</section>

app/views/rayadmin/performs/new.html.erb
<section class="content-header">
<h1>新規登録</h1>
</section>

<section class="content">
<%= render 'form' %>
</section>

app/views/rayadmin/performs/show.html.erb
<section class="content">
    <div class="box">
        <div class="box-header">
            <%= link_to 'Edit', edit_rayadmin_perform_path(@perform), {class:"btn btn-xs btn-success"} %> 
            <%= link_to 'Back', rayadmin_performs_path, {class:"btn btn-xs btn-primary"} %>
            <%= link_to 'Show', [:rayadmin, @perform], {class:"btn btn-xs btn-warning"} %>
            <%= link_to 'Destroy', [:rayadmin, @perform], method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-xs btn-danger" %>
        </div>
        <div class="box-body">
            
            <div class="col-md-9 col-md-9">
            	<div id="kamonarticle">
            	    <div class="kimg-box">
                          <%= image_tag @perform.performimage.url %>
                    </div>
                    <div class="kamontitle">
                        <h1><%= @perform.title %></h1>
                    </div>
                    <div class="kdiscription">
            		    <%== @perform.description %>
            		</div>
            	</div>
            </div>    

        </div>
    </div>
</section>